/*
 * Copyright (C) 2014 Khasdul
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.yf.kp.design.dialog.report;

import com.yf.kp.model.Angsuran;
import com.yf.kp.model.Bulanan;
import com.yf.kp.model.Kelas;
import com.yf.kp.model.Tunai;
import com.yf.kp.service.AngsuranService;
import com.yf.kp.service.BulananService;
import com.yf.kp.service.KelasService;
import com.yf.kp.service.TunaiService;
import com.yf.kp.service.impl.AngsuranServiceImpl;
import com.yf.kp.service.impl.BulananServiceImpl;
import com.yf.kp.service.impl.KelasServiceImpl;
import com.yf.kp.service.impl.TunaiServiceImpl;
import com.yf.kp.utility.Dbconnection;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Khasdul
 */
public class ReportTagihan extends java.awt.Dialog {

    /**
     * Creates new form ReportTagihan
     *
     * @param parent
     * @param modal
     */
    public ReportTagihan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    private void cetakTunai() {
        try {
            String path = "/com/yf/kp/report/tagihan/fix/LaporanTagihanTunai.jasper";
            HashMap map = new HashMap();
            map.put("kelas", cmbKelas.getSelectedItem().toString());
            map.put("namaTagihan", cmbNamaTagihan.getSelectedItem().toString());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(path), map, Dbconnection.connect());
            JasperViewer.viewReport(jasperPrint, false);
            this.dispose();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(ReportSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cetakAngsuran() {
        try {
            String path = "/com/yf/kp/report/tagihan/fix/TagiahanAngsuran.jasper";
            HashMap map = new HashMap();
            map.put("kelas", cmbKelas.getSelectedItem().toString());
            map.put("namaTagihan", cmbNamaTagihan.getSelectedItem().toString());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(path), map, Dbconnection.connect());
            JasperViewer.viewReport(jasperPrint, false);
            this.dispose();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(ReportSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cetakBulanan() {
        try {
            String path = "/com/yf/kp/report/tagihan/fix/TagihanBulanan.jasper";
            HashMap map = new HashMap();
            map.put("kelas", cmbKelas.getSelectedItem().toString());
            map.put("namaTagihan", cmbNamaTagihan.getSelectedItem().toString());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(path), map, Dbconnection.connect());
            JasperViewer.viewReport(jasperPrint, false);
            this.dispose();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(ReportSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void kelasLookup() {
        cmbKelas.removeAllItems();
        KelasService kelasService = new KelasServiceImpl();
        List<Kelas> kelasList = kelasService.findAll();
        for (Kelas kelas : kelasList) {
            cmbKelas.addItem(kelas.getNama_kelas());
        }
    }
    
    private void prepareCetak(){
        if (radAngsuran.isSelected()) {
            cetakAngsuran();
        } else if (radTunai.isSelected()){
            cetakTunai();
        } else if (radBulanan.isSelected()){
            cetakBulanan();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radAngsuran = new javax.swing.JRadioButton();
        radTunai = new javax.swing.JRadioButton();
        radBulanan = new javax.swing.JRadioButton();
        cmbKelas = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbNamaTagihan = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pilih tipe pembayaran"));

        buttonGroup1.add(radAngsuran);
        radAngsuran.setText("Angsuran");
        radAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAngsuranActionPerformed(evt);
            }
        });

        buttonGroup1.add(radTunai);
        radTunai.setText("Tunai");
        radTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTunaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBulanan);
        radBulanan.setText("Bulanan");
        radBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBulananActionPerformed(evt);
            }
        });

        jButton1.setText("Cetak");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(radAngsuran)
                .addGap(5, 5, 5)
                .addComponent(radTunai)
                .addGap(5, 5, 5)
                .addComponent(radBulanan)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbNamaTagihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAngsuran)
                    .addComponent(radTunai)
                    .addComponent(radBulanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbNamaTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAngsuranActionPerformed
        cmbNamaTagihan.removeAllItems();
        AngsuranService angsuranService = new AngsuranServiceImpl();
        List<Angsuran> listAngsuran = angsuranService.findAll();
        for (Angsuran angsuran : listAngsuran) {
            cmbNamaTagihan.addItem(angsuran.getNama());
        }
    }//GEN-LAST:event_radAngsuranActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        kelasLookup();
    }//GEN-LAST:event_formWindowOpened

    private void radTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTunaiActionPerformed
        cmbNamaTagihan.removeAllItems();
        TunaiService tunaiService = new TunaiServiceImpl();
        List<Tunai> listTunai = tunaiService.findAll();
        for (Tunai tunai : listTunai) {
            cmbNamaTagihan.addItem(tunai.getNama());
        }
    }//GEN-LAST:event_radTunaiActionPerformed

    private void radBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBulananActionPerformed
        cmbNamaTagihan.removeAllItems();
        BulananService bulananService = new BulananServiceImpl();
        List<Bulanan> listBulanan = bulananService.findAll();
        for (Bulanan bulanan : listBulanan) {
            cmbNamaTagihan.addItem(bulanan.getNama());
        }
    }//GEN-LAST:event_radBulananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prepareCetak();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbKelas;
    private javax.swing.JComboBox cmbNamaTagihan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radAngsuran;
    private javax.swing.JRadioButton radBulanan;
    private javax.swing.JRadioButton radTunai;
    // End of variables declaration//GEN-END:variables
}
