/*
 * Copyright (C) 2014 Khasdul
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.yf.kp.design.dialog.report;

import com.yf.kp.model.Angsuran;
import com.yf.kp.model.Bulanan;
import com.yf.kp.model.Tunai;
import com.yf.kp.service.AngsuranService;
import com.yf.kp.service.BulananService;
import com.yf.kp.service.TunaiService;
import com.yf.kp.service.impl.AngsuranServiceImpl;
import com.yf.kp.service.impl.BulananServiceImpl;
import com.yf.kp.service.impl.TunaiServiceImpl;
import com.yf.kp.utility.Dbconnection;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Khasdul
 */
public class ReportPembayaran extends javax.swing.JDialog {

    /**
     * Creates new form ReportPembayaran
     *
     * @param parent
     * @param modal
     */
    public ReportPembayaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    private void cetakAngsuran() {
        try {
            String path = "/com/yf/kp/report/pembayaran/fix/PembayaranAngsuran.jasper";
            HashMap map = new HashMap();
            map.put("namaPembayaran", cmbNamaPembayaran.getSelectedItem().toString());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(path), map, Dbconnection.connect());
            JasperViewer.viewReport(jasperPrint, false);
            this.dispose();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(ReportSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cetakBulanan() {
        try {
            String path = "/com/yf/kp/report/pembayaran/fix/PembayaranBulana.jasper";
            HashMap map = new HashMap();
            map.put("namaPembayaran", cmbNamaPembayaran.getSelectedItem().toString());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(path), map, Dbconnection.connect());
            JasperViewer.viewReport(jasperPrint, false);
            this.dispose();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(ReportSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cetakTunai() {
        try {
            String path = "/com/yf/kp/report/pembayaran/fix/tunai.jasper";
            HashMap map = new HashMap();
            map.put("namaPembayaran", cmbNamaPembayaran.getSelectedItem().toString());
            JasperPrint jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream(path), map, Dbconnection.connect());
            JasperViewer.viewReport(jasperPrint, false);
            this.dispose();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(ReportSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void prepareCetak() {
        if (radAngsuran.isSelected()) {
            cetakAngsuran();
        } else if (radTunai.isSelected()) {
            cetakTunai();
        } else if (radBulanan.isSelected()) {
            cetakBulanan();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbNamaPembayaran = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        radAngsuran = new javax.swing.JRadioButton();
        radTunai = new javax.swing.JRadioButton();
        radBulanan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pilih Nama Pembayaran"));

        jButton1.setText("Cetak");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radAngsuran);
        radAngsuran.setText("Angsuran");
        radAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAngsuranActionPerformed(evt);
            }
        });

        buttonGroup1.add(radTunai);
        radTunai.setText("Tunai");
        radTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTunaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBulanan);
        radBulanan.setText("Bulanan");
        radBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBulananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNamaPembayaran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(radAngsuran)
                .addGap(18, 18, 18)
                .addComponent(radTunai)
                .addGap(18, 18, 18)
                .addComponent(radBulanan)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAngsuran)
                    .addComponent(radTunai)
                    .addComponent(radBulanan))
                .addGap(18, 18, 18)
                .addComponent(cmbNamaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAngsuranActionPerformed
        cmbNamaPembayaran.removeAllItems();
        AngsuranService angsuranService = new AngsuranServiceImpl();
        List<Angsuran> listAngsuran = angsuranService.findAll();
        for (Angsuran angsuran : listAngsuran) {
            cmbNamaPembayaran.addItem(angsuran.getNama());
        }
    }//GEN-LAST:event_radAngsuranActionPerformed

    private void radTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTunaiActionPerformed
        // TODO add your handling code here:
        cmbNamaPembayaran.removeAllItems();
        TunaiService tunaiService = new TunaiServiceImpl();
        List<Tunai> listTunai = tunaiService.findAll();
        for (Tunai tunai : listTunai) {
            cmbNamaPembayaran.addItem(tunai.getNama());
        }
    }//GEN-LAST:event_radTunaiActionPerformed

    private void radBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBulananActionPerformed
        cmbNamaPembayaran.removeAllItems();
        BulananService bulananService = new BulananServiceImpl();
        List<Bulanan> listBulanan = bulananService.findAll();
        for (Bulanan bulanan : listBulanan) {
            cmbNamaPembayaran.addItem(bulanan.getNama());
        }
    }//GEN-LAST:event_radBulananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prepareCetak();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbNamaPembayaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radAngsuran;
    private javax.swing.JRadioButton radBulanan;
    private javax.swing.JRadioButton radTunai;
    // End of variables declaration//GEN-END:variables
}
